# 数据源配置
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springboot_test
  username: root
  password: root

# 加载并激活其他yml配置文件
spring:
  profiles:
    active: baidu, google
  # ----HikariCP连接池配置----
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_test
    username: root
    password: root

# 日志级别配置  对不同包中的类配置不同级别
logging:
  level:
    cn.yeats: debug
    org.springframework: info


# 端口配置  Spring Boot项目默认使用的端口是8080
server:
  port: 80  # 浏览器默认端口是80

# mybatis配置
mybatis:
  type-aliases-package: cn.yeats.pojo # 实体类所在包的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出执行的sql语句
# 映射文件路径。   使用mybatis时需要xml配置文件，通用Mapper就不再需要xml文件了
#  mapper-locations: classpath:mapper/*.xml